[package]
name = "chess"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[features]
default = ["fmt"]
fmt = []
online = ["serde"]

[dependencies]
simple-grid = "0.1.2"
serde = { version = "1.0.118", features = ["derive"], optional = true }
