[package]
name = "chess"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[features]
default = ["fmt"]
fmt = []

[dependencies]
simple-grid = { version = "1.0.1", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"], optional = true }
