[package]
name = "chess"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
simple-grid = "2.0.0"
serde = { version = "1.0.126", features = ["derive"], optional = true }
